### ISSUE TITLE
Unable to locate element.

### ISSUE THREAD

**Issue by adityathakurxd** [Estayparadox/InstaBot#6]
I tried running it on my system, but I am getting an error. 

```
DevTools listening on ws://127.0.0.1:53906/devtools/browser/f0152ab9-0c43-41ac-bb0c-bb0b9036406d
[6644:12600:0121/125942.184:ERROR:device_event_log_impl.cc(211)] [12:59:42.184] USB: usb_device_handle_win.cc:1020 Failed to 
read descriptor from node connection: A device attached to the system is not functioning. (0x1F)

Traceback (most recent call last):
  File "c:\Users\Asus\Documents\Insta-Bot-master\start.py", line 32, in <module>
    button_login = webdriver.find_element_by_xpath('//html//body//div[1]//section//main//div//article//div//div[1]//div//form//div//div[3]//button//div')
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 
394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 
976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 
321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Asus\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//html//body//div[1]//section//main//div//article//div//div[1]//div//form//div//div[3]//button//div"}
  (Session info: chrome=87.0.4280.141)
```
![start py - Insta-Bot-master - Visual Studio Code 1_21_2021 12_59_28 PM](https://user-images.githubusercontent.com/53579386/105317990-f53eb580-5be8-11eb-9b57-7d152538d051.png)

_The Chrome browser is launching fine and the credentials get filled in, but it is **unable to login**._

![Login • Instagram - Google Chrome 1_21_2021 12_59_53 PM](https://user-images.githubusercontent.com/53579386/105318097-169fa180-5be9-11eb-888f-4dbda94968ce.png)

**Comment by c0bra9** [comment]
solution?
